import {useEffect, useState} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css'

export default function Menu() {
  const router = useRouter()

  const items = ['about', 'bookshelf', 'musings', 'work'];

  return (
      <div className={styles.menubar}>
        <h1 className={styles.title}>Michael Bryce</h1>
        <meta name="description" content="Generated by create next app" />
        {items.map((item,index) => (
          <h2 key={index} onClick={() => router.push(`/${item}`)} className={styles.menuItem}>{item}</h2>))}
        <h2 rel="icon" href="/favicon.ico" />
      </div>
        )
}
