import React, {useEffect, useState} from 'react';
import {useRouter} from 'next/router';
import styles from '../styles/menu.module.css';
import {useTrail, a} from '@react-spring/web';

// function Trail({open, children}) {
//   const items = React.Children.toArray(children);
//   const trail = useTrail(items.length, {
//     config: {mass: 5, tension: 2000, friction: 200},
//     opacity: open ? 1 : 0,
//     x: open ? 0 : 20,
//     height: open ? 40 : 0,
//     from: {opacity: 0, x: 20, height: 0},
//   });
//   return (
//     <div>
//       {trail.map(({height, ...style}, index) => (
//         <a.div key={index} className={styles.trailsText} style={style}>
//           <a.div style={{height}}>{items[index]}</a.div>
//         </a.div>
//       ))}
//     </div>
//   );
// }

export default function Menu() {
  const router = useRouter();
  const [open, setOpen] = useState(false);

  // const items = ['about', 'bookshelf', 'musings', 'work'];
  const items = ['about', 'bookshelf', 'work'];

  useEffect(() => {
    setTimeout(() => {
      setOpen(true);
    }, 10);
  }, []);

  const navigate = (path) => {
    console.log('Current path:', router.pathname, 'New path name:', path);
    if (path !== router.pathname) {
      setOpen(false);
      setTimeout(() => {
        router.push(path);
      }, 200);
    }
  };

  return (
    <div className={styles.menubar}>
      <h1 className={styles.title} onClick={() => navigate('/')}>
        Michael Bryce
      </h1>
      <meta name="description" content="Generated by create next app" />
      {items.map((item, index) => (
        <h2
          key={index}
          onClick={() => {
            console.log('Current path:', router.pathname, 'New path name:', `/${item}`);
            navigate(`/${item}`);
          }}
          className={styles.menuItem}>
          {item}
        </h2>
      ))}
      <h2 rel="icon" href="/favicon.ico" />
    </div>
  );
}
